# Generated by Django 4.1 on 2022-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='内存SN号'),
        ),
    ]
